/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dog(props) {
    const { nodes, materials } = useGLTF("./models/dog/model.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.character_dog.geometry}
                material={materials["Beige.017"]}
                rotation={[Math.PI / 2, 0, 0]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.character_dogArmLeft.geometry}
                    material={materials["Beige.017"]}
                    position={[0.204, 0, -0.634]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.character_dogArmRight.geometry}
                    material={materials["Beige.017"]}
                    position={[-0.204, 0, -0.634]}
                />
                <group position={[0, 0, -0.704]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube1339.geometry}
                        material={materials["Beige.017"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube1339_1.geometry}
                        material={materials["Red.034"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube1339_2.geometry}
                        material={materials["Black.026"]}
                    />
                </group>
            </mesh>
        </group>
    );
}

useGLTF.preload("./models/dog/model.glb");